name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 16
          - 18
          - 20
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
        env:
          # https://github.com/actions/setup-node/issues/531#issuecomment-1819151412
          SKIP_YARN_COREPACK_CHECK: 1
          YARN_IGNORE_NODE: 1

      - name: Install Dependencies
        run: yarn --immutable
        env:
          SKIP_YARN_COREPACK_CHECK: 1
          YARN_IGNORE_NODE: 1

      - name: Build, Lint and Test
        run: |
          yarn build
          yarn lint
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true
          SKIP_YARN_COREPACK_CHECK: 1
          YARN_IGNORE_NODE: 1

      - name: Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
